{% set name = "igl" %}
{% set version = "2022.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nodtem66/libigl-python-bindings/archive/{{ version }}.tar.gz
  sha256: 74b6e22a83b8a70f5cc72fc621e45fba7415c2905eec676dbd3a09fb203bd71e

build:
  number: 0
  skip: true  # [py<31]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - libblas
    - libcblas
    - make
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - igl

about:
  home: https://libigl.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Simple python geometry processing library
  description: |
    libigl is a simple python and C++ geometry processing library.
    We have a wide functionality including construction of
    sparse discrete differential geometry operators and
    finite-elements matrices such as the cotangent Laplacian and
    diagonalized mass matrix, and
    simple facet and edge-based topology data structures.
  doc_url: https://libigl.github.io/libigl-python-bindings/
  dev_url: https://github.com/libigl/libigl-python-bindings

extra:
  recipe-maintainers:
    - teseoch
    - fwilliams
    - skoch9
    - danielepanozzo
    - nodtem66
