{% set name = "igl" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geometryprocessing/libigl-python-bindings/archive/{{ version }}.tar.gz
  sha256: 7cdd6d5d1f56b2ebf0ae3c6e5cd4b8a18c960865a28f2b98fb52eadc5076247e

build:
  number: 0
  skip: True  # [py<31]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - libblas
    - libcblas
    - make
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - igl

about:
  home: https://libigl.github.io
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.GPL
  summary: 'Simple python geometry processing library'
  description: |
    libigl is a simple python and C++ geometry processing library.
    We have a wide functionality including construction of
    sparse discrete differential geometry operators and
    finite-elements matrices such as the cotangent Laplacian and
    diagonalized mass matrix, and
    simple facet and edge-based topology data structures.
  doc_url: https://libigl.github.io/tutorial/
  dev_url: https://github.com/libigl/libigl/

extra:
  recipe-maintainers:
    - teseoch
    - fwilliams
    - skoch9
    - danielepanozzo
