provider:
  win: azure
conda_forge_output_validation: false
github:
  user_or_org: nodtem66
  branch_name: master
channels:
  sources:
    - conda-forge
    - defaults
  targets:
    - ["nodtem66", "main"]
