# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-
parameters:
- name: UPLOAD_PACKAGES
  type: string
  default: 'False'
- name: ENABLE
  type: boolean
  default: true
  
jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_numpy1.18python3.7.____cpython:
        CONFIG: osx_64_numpy1.18python3.7.____cpython
        UPLOAD_PACKAGES: ${{ parameters.UPLOAD_PACKAGES }}
      osx_64_numpy1.18python3.8.____cpython:
        CONFIG: osx_64_numpy1.18python3.8.____cpython
        UPLOAD_PACKAGES: ${{ parameters.UPLOAD_PACKAGES }}
      osx_64_numpy1.19python3.7.____73_pypy:
        CONFIG: osx_64_numpy1.19python3.7.____73_pypy
        UPLOAD_PACKAGES: ${{ parameters.UPLOAD_PACKAGES }}
      osx_64_numpy1.19python3.9.____cpython:
        CONFIG: osx_64_numpy1.19python3.9.____cpython
        UPLOAD_PACKAGES: ${{ parameters.UPLOAD_PACKAGES }}
  timeoutInMinutes: 360
  condition: eq('${{ parameters.ENABLE }}', 'true')
  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)